"""
analyze_pca_width.py
LIF parameter PCA analysis across scales — Width U-curve mechanistic analysis.

Reads: results/lif_params_all_scales.json  (generated by collect_lif_params.py)
Output: figures/lif_pca_width.png

4-panel figure:
  A: Effective threshold distribution per scale (violin)
  B: PCA on (threshold, leak, steepness) per head, colored by scale
  C: Layer-wise mean threshold per scale (heatmap)
  D: U-curve delta% overlay with LIF variance
"""

import sys
import os
import json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch

EMBER_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH  = os.path.join(EMBER_DIR, 'results', 'lif_params_all_scales.json')
OUT_PATH   = os.path.join(EMBER_DIR, 'figures', 'lif_pca_width.png')

# U-curve deltas from 3-seed experiments (Standard vs LIF, val loss delta%)
# Positive = LIF worse, Negative = LIF better
U_CURVE_DELTA = {
    'xs':     -0.10,
    'small':  +0.15,
    'medium': +0.35,
    'mid':    -0.26,
    'wide':   -0.12,
}

SCALE_COLORS = {
    'xs':     '#4477AA',
    'small':  '#66CCEE',
    'medium': '#CCBB44',
    'mid':    '#EE6677',
    'wide':   '#AA3377',
}

SCALE_LABELS = {
    'xs':     'XS (128d)',
    'small':  'S (192d)',
    'medium': 'M (256d)',
    'mid':    'Mid (320d)',
    'wide':   'W (384d)',
}


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def softplus(x):
    return np.log1p(np.exp(x))


def apply_forward(raw_val, param_type):
    """Apply model.py forward transform to raw nn.Parameter values."""
    arr = np.array(raw_val, dtype=float)
    if param_type == 'threshold':
        return np.abs(arr) * 0.1
    elif param_type == 'leak':
        return sigmoid(arr)
    elif param_type == 'steepness':
        return softplus(arr)
    return arr


def extract_params(lif_params, config):
    """
    Extract per-head parameter arrays organized by layer.
    Returns dict: {layer_idx: {'threshold': arr, 'leak': arr, 'steepness': arr}}
    """
    n_layer = config['n_layer']
    n_head  = config['n_head']

    layers = {}
    for i in range(n_layer):
        th_key = f'transformer.h.{i}.attn.threshold'
        lk_key = f'transformer.h.{i}.attn.leak'
        st_key = f'transformer.h.{i}.attn.steepness'

        if th_key not in lif_params:
            continue

        layers[i] = {
            'threshold':  apply_forward(lif_params[th_key],  'threshold'),
            'leak':       apply_forward(lif_params[lk_key],  'leak'),
            'steepness':  apply_forward(lif_params[st_key],  'steepness'),
        }
    return layers


def collect_head_vectors(scale_data):
    """
    Returns (N_heads × 3) array: [threshold, leak, steepness] per head.
    Also returns per-layer threshold means.
    """
    layers  = scale_data['layers']
    vectors = []
    layer_th_means = []

    for i in sorted(layers.keys()):
        th = layers[i]['threshold']
        lk = layers[i]['leak']
        st = layers[i]['steepness']
        for h in range(len(th)):
            vectors.append([th[h], lk[h], st[h]])
        layer_th_means.append(np.mean(th))

    return np.array(vectors), layer_th_means


def pca_2d(X):
    """Simple 2-component PCA without sklearn dependency."""
    X_c = X - X.mean(axis=0)
    cov = np.cov(X_c.T)
    vals, vecs = np.linalg.eigh(cov)
    # Sort descending
    idx = np.argsort(vals)[::-1]
    vecs = vecs[:, idx]
    pc = X_c @ vecs[:, :2]
    var_ratio = vals[idx[:2]] / vals.sum()
    return pc, var_ratio


def main():
    if not os.path.exists(JSON_PATH):
        print(f"ERROR: {JSON_PATH} not found.")
        print("Run collect_lif_params.py first.")
        sys.exit(1)

    with open(JSON_PATH) as f:
        all_data = json.load(f)

    scales = ['xs', 'small', 'medium', 'mid', 'wide']
    scales = [s for s in scales if s in all_data]

    if not scales:
        print("ERROR: No scale data found in JSON.")
        sys.exit(1)

    print(f"Loaded scales: {scales}")

    # Pre-process each scale
    processed = {}
    for scale in scales:
        d = all_data[scale]
        cfg = d['config']
        layers = extract_params(d['lif_params'], cfg)
        vectors, layer_th_means = collect_head_vectors({'layers': layers})
        processed[scale] = {
            'vectors':        vectors,       # (N_heads, 3)
            'layer_th_means': layer_th_means,
            'config':         cfg,
            'best_val_loss':  d['best_val_loss'],
            'n_lif_values':   d['n_lif_values'],
        }
        n_head  = cfg['n_head']
        n_layer = cfg['n_layer']
        print(f"  {scale}: {n_layer}L/{n_head}H/{cfg['n_embd']}d "
              f"-> {len(vectors)} head vectors")

    # ------------------------------------------------------------------ PCA
    all_vecs = np.vstack([processed[s]['vectors'] for s in scales])
    pcs_all, var_ratio = pca_2d(all_vecs)

    # Split back per scale
    ptr = 0
    for scale in scales:
        n = len(processed[scale]['vectors'])
        processed[scale]['pcs'] = pcs_all[ptr:ptr+n]
        ptr += n

    # ------------------------------------------------------------------ Plot
    fig = plt.figure(figsize=(16, 12))
    fig.patch.set_facecolor('#0D1117')
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.38, wspace=0.32)

    ax_A = fig.add_subplot(gs[0, 0])  # Threshold distribution
    ax_B = fig.add_subplot(gs[0, 1])  # PCA
    ax_C = fig.add_subplot(gs[1, 0])  # Layer-wise threshold heatmap
    ax_D = fig.add_subplot(gs[1, 1])  # U-curve + variance

    for ax in [ax_A, ax_B, ax_C, ax_D]:
        ax.set_facecolor('#161B22')
        for spine in ax.spines.values():
            spine.set_color('#30363D')
        ax.tick_params(colors='#8B949E', labelsize=9)
        ax.xaxis.label.set_color('#C9D1D9')
        ax.yaxis.label.set_color('#C9D1D9')
        ax.title.set_color('#E6EDF3')

    # ---- Panel A: Threshold violin per scale ----
    ax_A.set_title('A. Effective Threshold Distribution per Scale', fontsize=11, pad=8)
    violin_data = [processed[s]['vectors'][:, 0] for s in scales]
    vp = ax_A.violinplot(violin_data, positions=range(len(scales)),
                          showmedians=True, showextrema=True)
    for i, (pc, body) in enumerate(zip(scales, vp['bodies'])):
        body.set_facecolor(SCALE_COLORS[pc])
        body.set_alpha(0.7)
    vp['cmedians'].set_color('#FFFFFF')
    vp['cmins'].set_color('#8B949E')
    vp['cmaxes'].set_color('#8B949E')
    vp['cbars'].set_color('#8B949E')
    ax_A.set_xticks(range(len(scales)))
    ax_A.set_xticklabels([SCALE_LABELS[s] for s in scales], fontsize=8, rotation=15)
    ax_A.set_ylabel('Eff. Threshold (|θ|×0.1)', fontsize=9)
    ax_A.set_xlabel('Scale', fontsize=9)
    ax_A.axhline(0.001, color='#FFFFFF', lw=0.5, ls='--', alpha=0.3, label='init=0.001')
    ax_A.legend(fontsize=7, facecolor='#161B22', labelcolor='#8B949E', framealpha=0.5)

    # ---- Panel B: PCA scatter ----
    ax_B.set_title(f'B. PCA of LIF Head Parameters\n'
                   f'(PC1={var_ratio[0]:.1%}, PC2={var_ratio[1]:.1%})', fontsize=11, pad=8)
    for scale in scales:
        pcs = processed[scale]['pcs']
        ax_B.scatter(pcs[:, 0], pcs[:, 1],
                     c=SCALE_COLORS[scale], label=SCALE_LABELS[scale],
                     alpha=0.65, s=20, linewidths=0)

    legend_handles = [Patch(color=SCALE_COLORS[s], label=SCALE_LABELS[s]) for s in scales]
    ax_B.legend(handles=legend_handles, fontsize=8, facecolor='#161B22',
                labelcolor='#C9D1D9', framealpha=0.7, loc='best')
    ax_B.set_xlabel('PC1', fontsize=9)
    ax_B.set_ylabel('PC2', fontsize=9)
    ax_B.axhline(0, color='#30363D', lw=0.5)
    ax_B.axvline(0, color='#30363D', lw=0.5)

    # ---- Panel C: Layer-wise threshold mean heatmap ----
    ax_C.set_title('C. Layer-wise Mean Effective Threshold', fontsize=11, pad=8)

    # Pad to max layers
    max_layers = max(len(processed[s]['layer_th_means']) for s in scales)
    heat_data = []
    for scale in scales:
        row = processed[scale]['layer_th_means']
        padded = row + [np.nan] * (max_layers - len(row))
        heat_data.append(padded)

    heat_arr = np.array(heat_data)
    im = ax_C.imshow(heat_arr, aspect='auto', cmap='viridis',
                      interpolation='nearest')
    ax_C.set_yticks(range(len(scales)))
    ax_C.set_yticklabels([SCALE_LABELS[s] for s in scales], fontsize=8)
    ax_C.set_xlabel('Layer Index', fontsize=9)
    cbar = plt.colorbar(im, ax=ax_C, fraction=0.03, pad=0.02)
    cbar.set_label('Mean Threshold', color='#8B949E', fontsize=8)
    cbar.ax.tick_params(colors='#8B949E', labelsize=7)

    # Add value annotations
    for i in range(len(scales)):
        for j in range(max_layers):
            v = heat_arr[i, j]
            if not np.isnan(v):
                ax_C.text(j, i, f'{v:.3f}', ha='center', va='center',
                          fontsize=6, color='white' if v < heat_arr[~np.isnan(heat_arr)].mean() else 'black')

    # ---- Panel D: U-curve delta + threshold variance ----
    ax_D.set_title('D. U-Curve Delta% vs LIF Parameter Variance', fontsize=11, pad=8)

    widths   = []
    deltas   = []
    th_stds  = []
    lk_stds  = []
    st_stds  = []

    for scale in scales:
        cfg = processed[scale]['config']
        widths.append(cfg['n_embd'])
        deltas.append(U_CURVE_DELTA.get(scale, np.nan))
        vecs = processed[scale]['vectors']
        th_stds.append(np.std(vecs[:, 0]))
        lk_stds.append(np.std(vecs[:, 1]))
        st_stds.append(np.std(vecs[:, 2]))

    widths  = np.array(widths)
    deltas  = np.array(deltas)
    th_stds = np.array(th_stds)

    ax_D2 = ax_D.twinx()
    ax_D2.set_facecolor('#161B22')

    # Delta% bars
    bar_colors = ['#3FB950' if d < 0 else '#F85149' for d in deltas]
    ax_D.bar(widths, deltas, width=20, color=bar_colors, alpha=0.7,
              label='Δval% (neg=LIF better)')
    ax_D.axhline(0, color='#FFFFFF', lw=0.8, ls='--', alpha=0.5)
    ax_D.set_xlabel('Embedding Width (d)', fontsize=9)
    ax_D.set_ylabel('Val Loss Delta%', fontsize=9, color='#C9D1D9')
    ax_D.set_xticks(widths)
    ax_D.set_xticklabels([f'{w}d' for w in widths], fontsize=8)

    # Threshold std line on twin axis
    ax_D2.plot(widths, th_stds, 'o--', color='#FFA657', lw=1.5,
               markersize=6, label='Threshold Std')
    ax_D2.set_ylabel('Threshold Std (diversity)', fontsize=9, color='#FFA657')
    ax_D2.tick_params(axis='y', colors='#FFA657', labelsize=8)

    # Combined legend
    handles_D  = [Patch(color='#3FB950', label='LIF better (Δ<0)'),
                  Patch(color='#F85149', label='LIF worse  (Δ>0)'),
                  plt.Line2D([0], [0], color='#FFA657', lw=1.5, marker='o', label='Threshold Std')]
    ax_D.legend(handles=handles_D, fontsize=7, facecolor='#161B22',
                labelcolor='#C9D1D9', framealpha=0.7, loc='upper left')

    # Annotation: critical transition region
    ax_D.axvspan(256, 320, alpha=0.08, color='#FFFFFF', label='Critical zone')
    ax_D.text(288, min(deltas) * 0.9, 'Critical\nZone', ha='center',
              fontsize=7, color='#FFFFFF', alpha=0.5)

    # ---- Suptitle ----
    fig.suptitle('Ember LIF Gating — Width-Dependent Parameter Geometry\n'
                 'Mechanistic Analysis of U-Curve Reversal (256d→320d)',
                 fontsize=13, color='#E6EDF3', y=0.98)

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    plt.savefig(OUT_PATH, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    plt.close()
    print(f"\nSaved: {OUT_PATH}")

    # ---- Summary ----
    print("\n=== LIF Parameter Summary ===")
    print(f"{'Scale':<8} {'n_embd':>6} {'n_heads':>7} {'th_std':>8} {'lk_std':>8} {'st_std':>8} {'delta%':>8}")
    for i, scale in enumerate(scales):
        cfg  = processed[scale]['config']
        vecs = processed[scale]['vectors']
        print(f"{scale:<8} {cfg['n_embd']:>6} {cfg['n_head']:>7} "
              f"{np.std(vecs[:,0]):>8.4f} {np.std(vecs[:,1]):>8.4f} {np.std(vecs[:,2]):>8.4f} "
              f"{U_CURVE_DELTA.get(scale, float('nan')):>+8.2f}")


if __name__ == '__main__':
    main()
